apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sample-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/18
    services:
      cidrBlocks:
        - 10.96.0.0/12 # Doesn't matter because they are an internal network
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: RKE2ControlPlane
    name: sample-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: sample-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: sample-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 10.168.200.53 # Has to match the IP of the control plane node
    port: 6443
  noCloudProvider: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: RKE2ControlPlane
metadata:
  name: sample-cluster
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3MachineTemplate
    name: sample-cluster-controlplane
  replicas: 1
  serverConfig:
    cni: calico
    cniMultusEnable: true
  preRKE2Commands:
    - /usr/lib/systemd/systemd-growfs /var  # this is required to fix the bug (https://bugzilla.suse.com/show_bug.cgi?id=1217430)
    - curl -Lk https://raw.githubusercontent.com/k8snetworkplumbingwg/sriov-network-device-plugin/master/deployments/sriovdp-daemonset.yaml > /var/sriovdp-daemonset.yaml
  agentConfig:
    format: ignition
    additionalUserData:    # This is the butane content to be applied to the node (during ignition step)
      config: |         
        variant: fcos
        version: 1.4.0
        passwd:
          users:
           - name: root
             password_hash: "$y$j9T$/t4THH10B7esLiIVBROsE.$G1lyxfy/MoFVOrfXSnWAUq70Tf3mjfZBIe18koGOuXB"
        storage:
          links:
            - path: /var/sriovdp-daemonset.yaml
              overwrite: true
              target: /var/lib/rancher/rke2/server/manifests/sriovdp-daemonset.yaml
              hard: false
          files:
            - path: /var/lib/rancher/rke2/server/manifests/configmap-sriov.yaml
              overwrite: true
              contents:
                inline: |
                  apiVersion: v1
                  kind: ConfigMap
                  metadata:
                    name: sriovdp-config
                    namespace: kube-system
                  data:
                    config.json: |
                      {
                          "resourceList": [
                              {
                                  "resourceName": "intel_fec_5g",
                                  "devicetype": "accelerator",
                                  "selectors": {
                                      "vendors": ["8086"],
                                      "devices": ["0d5d"]
                                  }
                              },
                              {
                                  "resourceName": "intel_sriov_odu",
                                  "selectors": {
                                      "vendors": ["8086"],
                                      "devices": ["1889"],
                                      "drivers": ["vfio-pci"],
                                      "pfNames": ["p2p1"]
                                  }
                              },
                              {
                                  "resourceName": "intel_sriov_oru",
                                  "selectors": {
                                      "vendors": ["8086"],
                                      "devices": ["1889"],
                                      "drivers": ["vfio-pci"],
                                      "pfNames": ["p2p2"]
                                  }
                              }
                          ]
                      }
              mode: 0644
              user:
                name: root
              group:
                name: root
        kernel_arguments:
          should_exist:
            - intel_iommu=on
            - intel_pstate=passive
            - processor.max_cstate=1
            - intel_idle.max_cstate=0
            - iommu=pt
            - mce=off
            - hugepagesz=1G hugepages=40
            - hugepagesz=2M hugepages=0
            - default_hugepagesz=1G
            - kthread_cpus=0,31,32,63
            - irqaffinity=0,31,32,63
            - isolcpu=1-30,33-62
            - nohz_full=1-30,33-62
            - rcu_nocbs=1-30,33-62
            - rcu_nocb_poll
        systemd:
          units:
            - name: cpu-partitioning.service
              enabled: true
              contents: |
                [Unit]
                Description=cpu-partitioning
                Wants=network-online.target
                After=network.target network-online.target
                [Service]
                Type=oneshot
                User=root
                ExecStart=/bin/sh -c "echo isolated_cores=1-30,33-62 > /etc/tuned/cpu-partitioning-variables.conf"
                ExecStartPost=/bin/sh -c "tuned-adm profile cpu-partitioning"
                ExecStartPost=/bin/sh -c "systemctl enable tuned.service"
                [Install]
                WantedBy=multi-user.target
            - name: dpdk-vf-creation.service
              enabled: true
              contents: |
                [Unit]
                Description=DPDK VF creation service
                Wants=network-online.target
                After=network.target network-online.target
                [Service]
                User=root
                Type=forking
                TimeoutStartSec=900
                ExecStart=/bin/sh -c "modprobe igb_uio; modprobe vfio-pci"
                ExecStartPost=/bin/sh -c "dpdk-devbind.py -b igb_uio 0000:8a:00.0"
                ExecStartPost=/bin/sh -c "echo 2 > /sys/bus/pci/devices/0000:8a:00.0/max_vfs && dpdk-devbind.py -b vfio-pci 0000:8b:00.0"
                ExecStartPost=/bin/sh -c "pf_bb_config ACC100 -c /opt/pf-bb-config/acc100_config_vf_5g.cfg"
                ExecStartPost=/bin/sh -c "echo 4 > /sys/bus/pci/devices/0000:51:00.0/sriov_numvfs"
                ExecStartPost=/bin/sh -c "sleep 10"
                ExecStartPost=/bin/sh -c "ip link set p2p1 vf 0 mac 00:11:22:33:00:00 && ip link set p2p1 vf 1 mac 00:11:22:33:00:10 && ip link set p2p1 vf 2 mac 00:11:22:33:00:20 && ip link set p2p1 vf 3 mac 00:11:22:33:00:30"
                ExecStartPost=/bin/sh -c "echo 4 > /sys/bus/pci/devices/0000:51:00.1/sriov_numvfs"
                ExecStartPost=/bin/sh -c "sleep 10"
                ExecStartPost=/bin/sh -c "ip link set p2p2 vf 0 mac 00:11:22:33:00:01 && ip link set p2p2 vf 1 mac 00:11:22:33:00:11 && ip link set p2p2 vf 2 mac 00:11:22:33:00:21 && ip link set p2p2 vf 3 mac 00:11:22:33:00:31"
                ExecStartPost=/bin/sh -c "dpdk-devbind.py -b vfio-pci 0000:51:11.0 0000:51:11.1 0000:51:11.2 0000:51:11.3 0000:51:01.0 0000:51:01.1 0000:51:01.2 0000:51:01.3"                RemainAfterExit=yes
                KillMode=process
                [Install]
                WantedBy=multi-user.target
    kubelet:
      extraArgs:
        - provider-id=metal3://{{ ds.meta_data.uuid }}
    version: v1.28.3+rke2r2   # Has to be the compatible with the management cluster
    nodeName: "{{ ds.meta_data.local_hostname }}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: sample-cluster-controlplane
  namespace: default
spec:
  template:
    spec:
      dataTemplate:
        name: sample-cluster-controlplane-template
      hostSelector:
        matchLabels:
          cluster-role: control-plane
      image:
        checksum: http://media.suse.baremetal/eib-image-telco-slemicro55.raw.md5sum
        checksumType: md5
        format: raw
        url: http://media.suse.baremetal/eib-image-telco-slemicro55.raw
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: sample-cluster-controlplane-template
  namespace: default
spec:
  clusterName: sample-cluster
  metaData:
    objectNames:
      - key: name
        object: machine
      - key: local-hostname
        object: machine
      - key: local_hostname
        object: machine
  networkData:
    links:
      ethernets:
        - id: eth0
          macAddress:
            fromHostInterface: eth0
          type: phy
    networks:
      ipv4DHCP:
        - id: eth0
          link: eth0
          routes:
            - gateway:
                string: 10.168.200.1
              network: 0.0.0.0
              prefix: 0
    services:
      dns:
        - 10.168.200.1
