---
- name: Include OS family vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Include OS distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "main.yml"

- name: Include platform-specific common tasks
  include_tasks: "_{{ ansible_os_family | lower }}.yml"

- name: Install required python packages
  become: yes
  pip:
    name: [diskimage-builder, ironic-python-agent-builder]
    state: latest

- name: Check to see if media server is deployed
  stat:
    path: /opt/media
  register: check_media_dir_result

- name: Build customer ipa for debugging
  include_tasks: build_debug_ipa_images.yml
  when:
    - build_debug_ipa_images | bool
    - check_media_dir_result.stat.isdir is defined
    - check_media_dir_result.stat.isdir

- name: Build sample user images
  include_tasks: build_sample_user_images.yml
  when:
    - build_sample_user_images | bool
    - check_media_dir_result.stat.isdir is defined
    - check_media_dir_result.stat.isdir

- name: Build metal3 images
  include_tasks: build_metal3_images.yml
  when:
    - build_metal3_images | bool
    - check_media_dir_result.stat.isdir is defined
    - check_media_dir_result.stat.isdir

- name: Build metal3 telco images
  include_tasks: build_metal3_telco_images.yml
  when:
    - build_metal3_telco_images | bool
    - check_media_dir_result.stat.isdir is defined
    - check_media_dir_result.stat.isdir
